/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as McpWeatherRouteImport } from './routes/mcp/weather'
import { Route as McpRagRouteImport } from './routes/mcp/rag'
import { Route as McpMusicRouteImport } from './routes/mcp/music'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api-keys'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as McpWeatherMessageRouteImport } from './routes/mcp/weather.message'
import { Route as McpRagMessageRouteImport } from './routes/mcp/rag.message'
import { Route as McpMusicMessageRouteImport } from './routes/mcp/music.message'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpWeatherRoute = McpWeatherRouteImport.update({
  id: '/mcp/weather',
  path: '/mcp/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRagRoute = McpRagRouteImport.update({
  id: '/mcp/rag',
  path: '/mcp/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const McpMusicRoute = McpMusicRouteImport.update({
  id: '/mcp/music',
  path: '/mcp/music',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/dashboard/team',
  path: '/dashboard/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/dashboard/services',
  path: '/dashboard/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/dashboard/api-keys',
  path: '/dashboard/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpWeatherMessageRoute = McpWeatherMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => McpWeatherRoute,
} as any)
const McpRagMessageRoute = McpRagMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => McpRagRoute,
} as any)
const McpMusicMessageRoute = McpMusicMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => McpMusicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/mcp/music': typeof McpMusicRouteWithChildren
  '/mcp/rag': typeof McpRagRouteWithChildren
  '/mcp/weather': typeof McpWeatherRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/mcp/music/message': typeof McpMusicMessageRoute
  '/mcp/rag/message': typeof McpRagMessageRoute
  '/mcp/weather/message': typeof McpWeatherMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/mcp/music': typeof McpMusicRouteWithChildren
  '/mcp/rag': typeof McpRagRouteWithChildren
  '/mcp/weather': typeof McpWeatherRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/mcp/music/message': typeof McpMusicMessageRoute
  '/mcp/rag/message': typeof McpRagMessageRoute
  '/mcp/weather/message': typeof McpWeatherMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/mcp/music': typeof McpMusicRouteWithChildren
  '/mcp/rag': typeof McpRagRouteWithChildren
  '/mcp/weather': typeof McpWeatherRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/mcp/music/message': typeof McpMusicMessageRoute
  '/mcp/rag/message': typeof McpRagMessageRoute
  '/mcp/weather/message': typeof McpWeatherMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-keys'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/mcp/music'
    | '/mcp/rag'
    | '/mcp/weather'
    | '/dashboard/'
    | '/api/auth/$'
    | '/mcp/music/message'
    | '/mcp/rag/message'
    | '/mcp/weather/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-keys'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/mcp/music'
    | '/mcp/rag'
    | '/mcp/weather'
    | '/dashboard'
    | '/api/auth/$'
    | '/mcp/music/message'
    | '/mcp/rag/message'
    | '/mcp/weather/message'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-keys'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/mcp/music'
    | '/mcp/rag'
    | '/mcp/weather'
    | '/dashboard/'
    | '/api/auth/$'
    | '/mcp/music/message'
    | '/mcp/rag/message'
    | '/mcp/weather/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  McpMusicRoute: typeof McpMusicRouteWithChildren
  McpRagRoute: typeof McpRagRouteWithChildren
  McpWeatherRoute: typeof McpWeatherRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/weather': {
      id: '/mcp/weather'
      path: '/mcp/weather'
      fullPath: '/mcp/weather'
      preLoaderRoute: typeof McpWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/rag': {
      id: '/mcp/rag'
      path: '/mcp/rag'
      fullPath: '/mcp/rag'
      preLoaderRoute: typeof McpRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/music': {
      id: '/mcp/music'
      path: '/mcp/music'
      fullPath: '/mcp/music'
      preLoaderRoute: typeof McpMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/dashboard/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/dashboard/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/weather/message': {
      id: '/mcp/weather/message'
      path: '/message'
      fullPath: '/mcp/weather/message'
      preLoaderRoute: typeof McpWeatherMessageRouteImport
      parentRoute: typeof McpWeatherRoute
    }
    '/mcp/rag/message': {
      id: '/mcp/rag/message'
      path: '/message'
      fullPath: '/mcp/rag/message'
      preLoaderRoute: typeof McpRagMessageRouteImport
      parentRoute: typeof McpRagRoute
    }
    '/mcp/music/message': {
      id: '/mcp/music/message'
      path: '/message'
      fullPath: '/mcp/music/message'
      preLoaderRoute: typeof McpMusicMessageRouteImport
      parentRoute: typeof McpMusicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface McpMusicRouteChildren {
  McpMusicMessageRoute: typeof McpMusicMessageRoute
}

const McpMusicRouteChildren: McpMusicRouteChildren = {
  McpMusicMessageRoute: McpMusicMessageRoute,
}

const McpMusicRouteWithChildren = McpMusicRoute._addFileChildren(
  McpMusicRouteChildren,
)

interface McpRagRouteChildren {
  McpRagMessageRoute: typeof McpRagMessageRoute
}

const McpRagRouteChildren: McpRagRouteChildren = {
  McpRagMessageRoute: McpRagMessageRoute,
}

const McpRagRouteWithChildren =
  McpRagRoute._addFileChildren(McpRagRouteChildren)

interface McpWeatherRouteChildren {
  McpWeatherMessageRoute: typeof McpWeatherMessageRoute
}

const McpWeatherRouteChildren: McpWeatherRouteChildren = {
  McpWeatherMessageRoute: McpWeatherMessageRoute,
}

const McpWeatherRouteWithChildren = McpWeatherRoute._addFileChildren(
  McpWeatherRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  McpMusicRoute: McpMusicRouteWithChildren,
  McpRagRoute: McpRagRouteWithChildren,
  McpWeatherRoute: McpWeatherRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
