/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as McpWeatherRouteImport } from './routes/mcp/weather'
import { Route as McpRagRouteImport } from './routes/mcp/rag'
import { Route as McpNewsRouteImport } from './routes/mcp/news'
import { Route as McpMusicRouteImport } from './routes/mcp/music'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardNewsRouteImport } from './routes/dashboard/news'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api-keys'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardKnowledgeBaseIndexRouteImport } from './routes/dashboard/knowledge-base/index'
import { Route as ApiKnowledgeBaseIndexRouteImport } from './routes/api/knowledge-base/index'
import { Route as McpWeatherMessageRouteImport } from './routes/mcp/weather.message'
import { Route as McpRagMessageRouteImport } from './routes/mcp/rag.message'
import { Route as McpNewsMessageRouteImport } from './routes/mcp/news.message'
import { Route as McpMusicMessageRouteImport } from './routes/mcp/music.message'
import { Route as DashboardKnowledgeBaseIdRouteImport } from './routes/dashboard/knowledge-base/$id'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api/tasks/$taskId'
import { Route as ApiKnowledgeBaseIdRouteImport } from './routes/api/knowledge-base/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiKnowledgeBaseIdFilesRouteImport } from './routes/api/knowledge-base/$id.files'
import { Route as ApiKnowledgeBaseIdFilesFileIdRouteImport } from './routes/api/knowledge-base/$id.files.$fileId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const McpWeatherRoute = McpWeatherRouteImport.update({
  id: '/mcp/weather',
  path: '/mcp/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRagRoute = McpRagRouteImport.update({
  id: '/mcp/rag',
  path: '/mcp/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const McpNewsRoute = McpNewsRouteImport.update({
  id: '/mcp/news',
  path: '/mcp/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpMusicRoute = McpMusicRouteImport.update({
  id: '/mcp/music',
  path: '/mcp/music',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKnowledgeBaseIndexRoute =
  DashboardKnowledgeBaseIndexRouteImport.update({
    id: '/knowledge-base/',
    path: '/knowledge-base/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiKnowledgeBaseIndexRoute = ApiKnowledgeBaseIndexRouteImport.update({
  id: '/api/knowledge-base/',
  path: '/api/knowledge-base/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpWeatherMessageRoute = McpWeatherMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => McpWeatherRoute,
} as any)
const McpRagMessageRoute = McpRagMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => McpRagRoute,
} as any)
const McpNewsMessageRoute = McpNewsMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => McpNewsRoute,
} as any)
const McpMusicMessageRoute = McpMusicMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => McpMusicRoute,
} as any)
const DashboardKnowledgeBaseIdRoute =
  DashboardKnowledgeBaseIdRouteImport.update({
    id: '/knowledge-base/$id',
    path: '/knowledge-base/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/api/tasks/$taskId',
  path: '/api/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeBaseIdRoute = ApiKnowledgeBaseIdRouteImport.update({
  id: '/api/knowledge-base/$id',
  path: '/api/knowledge-base/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeBaseIdFilesRoute = ApiKnowledgeBaseIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ApiKnowledgeBaseIdRoute,
} as any)
const ApiKnowledgeBaseIdFilesFileIdRoute =
  ApiKnowledgeBaseIdFilesFileIdRouteImport.update({
    id: '/$fileId',
    path: '/$fileId',
    getParentRoute: () => ApiKnowledgeBaseIdFilesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/mcp/music': typeof McpMusicRouteWithChildren
  '/mcp/news': typeof McpNewsRouteWithChildren
  '/mcp/rag': typeof McpRagRouteWithChildren
  '/mcp/weather': typeof McpWeatherRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/knowledge-base/$id': typeof ApiKnowledgeBaseIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/dashboard/knowledge-base/$id': typeof DashboardKnowledgeBaseIdRoute
  '/mcp/music/message': typeof McpMusicMessageRoute
  '/mcp/news/message': typeof McpNewsMessageRoute
  '/mcp/rag/message': typeof McpRagMessageRoute
  '/mcp/weather/message': typeof McpWeatherMessageRoute
  '/api/knowledge-base/': typeof ApiKnowledgeBaseIndexRoute
  '/dashboard/knowledge-base/': typeof DashboardKnowledgeBaseIndexRoute
  '/api/knowledge-base/$id/files': typeof ApiKnowledgeBaseIdFilesRouteWithChildren
  '/api/knowledge-base/$id/files/$fileId': typeof ApiKnowledgeBaseIdFilesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/mcp/music': typeof McpMusicRouteWithChildren
  '/mcp/news': typeof McpNewsRouteWithChildren
  '/mcp/rag': typeof McpRagRouteWithChildren
  '/mcp/weather': typeof McpWeatherRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/knowledge-base/$id': typeof ApiKnowledgeBaseIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/dashboard/knowledge-base/$id': typeof DashboardKnowledgeBaseIdRoute
  '/mcp/music/message': typeof McpMusicMessageRoute
  '/mcp/news/message': typeof McpNewsMessageRoute
  '/mcp/rag/message': typeof McpRagMessageRoute
  '/mcp/weather/message': typeof McpWeatherMessageRoute
  '/api/knowledge-base': typeof ApiKnowledgeBaseIndexRoute
  '/dashboard/knowledge-base': typeof DashboardKnowledgeBaseIndexRoute
  '/api/knowledge-base/$id/files': typeof ApiKnowledgeBaseIdFilesRouteWithChildren
  '/api/knowledge-base/$id/files/$fileId': typeof ApiKnowledgeBaseIdFilesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/mcp/music': typeof McpMusicRouteWithChildren
  '/mcp/news': typeof McpNewsRouteWithChildren
  '/mcp/rag': typeof McpRagRouteWithChildren
  '/mcp/weather': typeof McpWeatherRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/knowledge-base/$id': typeof ApiKnowledgeBaseIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/dashboard/knowledge-base/$id': typeof DashboardKnowledgeBaseIdRoute
  '/mcp/music/message': typeof McpMusicMessageRoute
  '/mcp/news/message': typeof McpNewsMessageRoute
  '/mcp/rag/message': typeof McpRagMessageRoute
  '/mcp/weather/message': typeof McpWeatherMessageRoute
  '/api/knowledge-base/': typeof ApiKnowledgeBaseIndexRoute
  '/dashboard/knowledge-base/': typeof DashboardKnowledgeBaseIndexRoute
  '/api/knowledge-base/$id/files': typeof ApiKnowledgeBaseIdFilesRouteWithChildren
  '/api/knowledge-base/$id/files/$fileId': typeof ApiKnowledgeBaseIdFilesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-keys'
    | '/dashboard/news'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/mcp/music'
    | '/mcp/news'
    | '/mcp/rag'
    | '/mcp/weather'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/knowledge-base/$id'
    | '/api/tasks/$taskId'
    | '/dashboard/knowledge-base/$id'
    | '/mcp/music/message'
    | '/mcp/news/message'
    | '/mcp/rag/message'
    | '/mcp/weather/message'
    | '/api/knowledge-base/'
    | '/dashboard/knowledge-base/'
    | '/api/knowledge-base/$id/files'
    | '/api/knowledge-base/$id/files/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-keys'
    | '/dashboard/news'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/mcp/music'
    | '/mcp/news'
    | '/mcp/rag'
    | '/mcp/weather'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/knowledge-base/$id'
    | '/api/tasks/$taskId'
    | '/dashboard/knowledge-base/$id'
    | '/mcp/music/message'
    | '/mcp/news/message'
    | '/mcp/rag/message'
    | '/mcp/weather/message'
    | '/api/knowledge-base'
    | '/dashboard/knowledge-base'
    | '/api/knowledge-base/$id/files'
    | '/api/knowledge-base/$id/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-keys'
    | '/dashboard/news'
    | '/dashboard/services'
    | '/dashboard/team'
    | '/mcp/music'
    | '/mcp/news'
    | '/mcp/rag'
    | '/mcp/weather'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/knowledge-base/$id'
    | '/api/tasks/$taskId'
    | '/dashboard/knowledge-base/$id'
    | '/mcp/music/message'
    | '/mcp/news/message'
    | '/mcp/rag/message'
    | '/mcp/weather/message'
    | '/api/knowledge-base/'
    | '/dashboard/knowledge-base/'
    | '/api/knowledge-base/$id/files'
    | '/api/knowledge-base/$id/files/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  McpMusicRoute: typeof McpMusicRouteWithChildren
  McpNewsRoute: typeof McpNewsRouteWithChildren
  McpRagRoute: typeof McpRagRouteWithChildren
  McpWeatherRoute: typeof McpWeatherRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiKnowledgeBaseIdRoute: typeof ApiKnowledgeBaseIdRouteWithChildren
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRoute
  ApiKnowledgeBaseIndexRoute: typeof ApiKnowledgeBaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/mcp/weather': {
      id: '/mcp/weather'
      path: '/mcp/weather'
      fullPath: '/mcp/weather'
      preLoaderRoute: typeof McpWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/rag': {
      id: '/mcp/rag'
      path: '/mcp/rag'
      fullPath: '/mcp/rag'
      preLoaderRoute: typeof McpRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/news': {
      id: '/mcp/news'
      path: '/mcp/news'
      fullPath: '/mcp/news'
      preLoaderRoute: typeof McpNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/music': {
      id: '/mcp/music'
      path: '/mcp/music'
      fullPath: '/mcp/music'
      preLoaderRoute: typeof McpMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/news': {
      id: '/dashboard/news'
      path: '/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/knowledge-base/': {
      id: '/dashboard/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/dashboard/knowledge-base/'
      preLoaderRoute: typeof DashboardKnowledgeBaseIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/knowledge-base/': {
      id: '/api/knowledge-base/'
      path: '/api/knowledge-base'
      fullPath: '/api/knowledge-base/'
      preLoaderRoute: typeof ApiKnowledgeBaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/weather/message': {
      id: '/mcp/weather/message'
      path: '/message'
      fullPath: '/mcp/weather/message'
      preLoaderRoute: typeof McpWeatherMessageRouteImport
      parentRoute: typeof McpWeatherRoute
    }
    '/mcp/rag/message': {
      id: '/mcp/rag/message'
      path: '/message'
      fullPath: '/mcp/rag/message'
      preLoaderRoute: typeof McpRagMessageRouteImport
      parentRoute: typeof McpRagRoute
    }
    '/mcp/news/message': {
      id: '/mcp/news/message'
      path: '/message'
      fullPath: '/mcp/news/message'
      preLoaderRoute: typeof McpNewsMessageRouteImport
      parentRoute: typeof McpNewsRoute
    }
    '/mcp/music/message': {
      id: '/mcp/music/message'
      path: '/message'
      fullPath: '/mcp/music/message'
      preLoaderRoute: typeof McpMusicMessageRouteImport
      parentRoute: typeof McpMusicRoute
    }
    '/dashboard/knowledge-base/$id': {
      id: '/dashboard/knowledge-base/$id'
      path: '/knowledge-base/$id'
      fullPath: '/dashboard/knowledge-base/$id'
      preLoaderRoute: typeof DashboardKnowledgeBaseIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/api/tasks/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-base/$id': {
      id: '/api/knowledge-base/$id'
      path: '/api/knowledge-base/$id'
      fullPath: '/api/knowledge-base/$id'
      preLoaderRoute: typeof ApiKnowledgeBaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-base/$id/files': {
      id: '/api/knowledge-base/$id/files'
      path: '/files'
      fullPath: '/api/knowledge-base/$id/files'
      preLoaderRoute: typeof ApiKnowledgeBaseIdFilesRouteImport
      parentRoute: typeof ApiKnowledgeBaseIdRoute
    }
    '/api/knowledge-base/$id/files/$fileId': {
      id: '/api/knowledge-base/$id/files/$fileId'
      path: '/$fileId'
      fullPath: '/api/knowledge-base/$id/files/$fileId'
      preLoaderRoute: typeof ApiKnowledgeBaseIdFilesFileIdRouteImport
      parentRoute: typeof ApiKnowledgeBaseIdFilesRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardKnowledgeBaseIdRoute: typeof DashboardKnowledgeBaseIdRoute
  DashboardKnowledgeBaseIndexRoute: typeof DashboardKnowledgeBaseIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardKnowledgeBaseIdRoute: DashboardKnowledgeBaseIdRoute,
  DashboardKnowledgeBaseIndexRoute: DashboardKnowledgeBaseIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface McpMusicRouteChildren {
  McpMusicMessageRoute: typeof McpMusicMessageRoute
}

const McpMusicRouteChildren: McpMusicRouteChildren = {
  McpMusicMessageRoute: McpMusicMessageRoute,
}

const McpMusicRouteWithChildren = McpMusicRoute._addFileChildren(
  McpMusicRouteChildren,
)

interface McpNewsRouteChildren {
  McpNewsMessageRoute: typeof McpNewsMessageRoute
}

const McpNewsRouteChildren: McpNewsRouteChildren = {
  McpNewsMessageRoute: McpNewsMessageRoute,
}

const McpNewsRouteWithChildren =
  McpNewsRoute._addFileChildren(McpNewsRouteChildren)

interface McpRagRouteChildren {
  McpRagMessageRoute: typeof McpRagMessageRoute
}

const McpRagRouteChildren: McpRagRouteChildren = {
  McpRagMessageRoute: McpRagMessageRoute,
}

const McpRagRouteWithChildren =
  McpRagRoute._addFileChildren(McpRagRouteChildren)

interface McpWeatherRouteChildren {
  McpWeatherMessageRoute: typeof McpWeatherMessageRoute
}

const McpWeatherRouteChildren: McpWeatherRouteChildren = {
  McpWeatherMessageRoute: McpWeatherMessageRoute,
}

const McpWeatherRouteWithChildren = McpWeatherRoute._addFileChildren(
  McpWeatherRouteChildren,
)

interface ApiKnowledgeBaseIdFilesRouteChildren {
  ApiKnowledgeBaseIdFilesFileIdRoute: typeof ApiKnowledgeBaseIdFilesFileIdRoute
}

const ApiKnowledgeBaseIdFilesRouteChildren: ApiKnowledgeBaseIdFilesRouteChildren =
  {
    ApiKnowledgeBaseIdFilesFileIdRoute: ApiKnowledgeBaseIdFilesFileIdRoute,
  }

const ApiKnowledgeBaseIdFilesRouteWithChildren =
  ApiKnowledgeBaseIdFilesRoute._addFileChildren(
    ApiKnowledgeBaseIdFilesRouteChildren,
  )

interface ApiKnowledgeBaseIdRouteChildren {
  ApiKnowledgeBaseIdFilesRoute: typeof ApiKnowledgeBaseIdFilesRouteWithChildren
}

const ApiKnowledgeBaseIdRouteChildren: ApiKnowledgeBaseIdRouteChildren = {
  ApiKnowledgeBaseIdFilesRoute: ApiKnowledgeBaseIdFilesRouteWithChildren,
}

const ApiKnowledgeBaseIdRouteWithChildren =
  ApiKnowledgeBaseIdRoute._addFileChildren(ApiKnowledgeBaseIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  McpMusicRoute: McpMusicRouteWithChildren,
  McpNewsRoute: McpNewsRouteWithChildren,
  McpRagRoute: McpRagRouteWithChildren,
  McpWeatherRoute: McpWeatherRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiKnowledgeBaseIdRoute: ApiKnowledgeBaseIdRouteWithChildren,
  ApiTasksTaskIdRoute: ApiTasksTaskIdRoute,
  ApiKnowledgeBaseIndexRoute: ApiKnowledgeBaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
